- hosts: all 
  tasks:
  - name: grouping host by distribution
    group_by: 
      key: srv_{{ansible_distribution}}
  - name: get server group by environmet 
    group_by:
      key: srv_{{ansible_local.custom.general.environment}}
  - name: get server group by environmet 
    group_by:
      key: app_{{ansible_local.custom.general.application}}
  - name: show hosts in dynamic inventory 
    debug:
      var: groups     
- hosts: srv_CentOs,&app_tomcat
  tasks:
  - name: Show the hosts list  
    debug: 
      msg: "{{ inventory_hostname }}"
