- hosts: all 
  tasks:
  - name: grouping host by distribution
    group_by: 
      key: srv_{{ansible_distribution}}
  - name: get server group by environmet 
    group_by:
      key: env_{{ansible_local.custom.general.environment}}
  - name: get server group by environmet 
    group_by:
      key: app_{{ansible_local.custom.general.application}}
  - name: show hosts in dynamic inventory 
    debug:
      var: groups  
      
### Getting user choices 

  - name: Setting environment fact 
    set_fact: 
       env: "env_{{env}}"
    when: env != 'all'
    
  - name: Setting srv fact 
    set_fact: 
       srv: "srv_{{srv}}"
    when: srv != 'all'
    
  - name: Setting appl fact 
    set_fact: 
       app: "app_{{app}}"
    when: app != 'all'


### Showing the list of hosts 
- hosts: "{{srv}},&{{app}},&{{env}}"
  tasks:
  - name: Show the hosts list  
    debug: 
      msg: "{{ inventory_hostname }}"
