- hosts: all 
  tasks:
  - name: prepare inventory based on User criteria 
    include_tasks: detect_target.yml  
### Showing the list of hosts 
- hosts: target_hosts
  tasks:
  - name: Show the hosts list  
    debug: 
      msg: "{{ inventory_hostname }}"
