- hosts: all 
  tasks:
  - name: grouping host by distribution
    group_by: 
      key: srv_{{ansible_distribution}}
  - name: get server group by environmet 
    group_by:
      key: env_{{ansible_local.custom.general.environment}}
  - name: get server group by environmet 
    group_by:
      key: app_{{ansible_local.custom.general.application}}"
  - name: show hosts in dynamic inventory 
    debug:
      var: groups  
      
### Getting user choices 

  - name: Setting environment fact 
    set_fact: 
       inv_env: "{{ lookup("vars", "groups['env_" + env + "']") }}"
    when: env != 'all'
  - name: Setting environment fact 
    set_fact: 
       inv_env: "{{groups['all']}}"
    when: env == 'all'
  
  - name: Show variable content 
    debug:
      var: inv_env 
    
### Showing the list of hosts 
#- hosts: '{{host_pat}}'
#  tasks:
#  - name: Show the hosts list  
#    debug: 
#      msg: "{{ inventory_hostname }}"
